language: python
script:
  - ./_travis/run.sh
before_install:
  - openssl version
after_success:
  - ./_travis/upload_coverage.sh
cache:
  directories:
  - ${HOME}/.cache
install:
  - ./_travis/install.sh
notifications:
  email: false
env:
  global:
    - GAE_SDK_PATH=${HOME}/.cache/google_appengine
    - PYTHONWARNINGS=always::DeprecationWarning

# https://github.com/travis-ci/travis-ci/issues/4794
matrix:
  include:
    - python: 2.6
      env: TOXENV=py26
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: pypy-5.4
      env: TOXENV=pypy
  allow_failures:
  - python: pypy-5.4
sudo: false
