shallow_clone: true
skip_branch_with_pr: true
build: off

environment:

  matrix:
    - python: "C:/Python26-x64"
    - python: "C:/Python26"
    - python: "C:/Python27-x64"
    - python: "C:/Python27"
    - python: "C:/Python34-x64"
    - python: "C:/Python34"
    - python: "C:/Python35-x64"
    - python: "C:/Python35"
    - python: "C:/Python36-x64"
    - python: "C:/Python36"

cache:
  - C:\Users\appveyor\AppData\Local\pip\Cache

init:
  - ps: $Env:path = $Env:python + ";" + $Env:python + "\scripts;" + $Env:path
install:
  - ps: pip install --upgrade pip wheel
  - ps: pip --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"

  - cmd: pip install -r dev-requirements.txt

build_script:
  - cmd: pip install .[secure,socks]

test_script:
  - ps: cd test
  - ps: pytest -vsx .
